# Generated by Django 4.0 on 2021-12-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_remove_link_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
