# Generated by Django 4.0 on 2022-01-08 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
